spring.application.name=coupon
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/coupon?serverTimezone=UTC&characterEncoding=UTF-8}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:coupon}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:coupon}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.flyway.enabled=true

server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=lax
